functions:
  user-api:
    handler: "lambda_function.lambda_handler"
    runtime: "python3.10"
    memory_size: 256
    timeout: 10
    environment_variables: {}
    filename: "../../src/user-api/user-api-lambda.zip"

  order-processor:
    handler: "processor.lambda_handler"
    runtime: "python3.10"
    memory_size: 512
    timeout: 30
    environment_variables: {}
    filename: "../../src/order-processor/order-processor.zip"
