functions:
  user-api:
    filename: "../src/user-api.zip"
    handler: "lambda_function.lambda_handler"
    runtime: "python3.11"
    memory_size: 128
    timeout: 3

  order-processor:
    filename: "../src/order-processor.zip"
    handler: "processor.lambda_handler"
    runtime: "python3.11"
    memory_size: 128
    timeout: 3
